# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-04 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('json_message', models.CharField(max_length=100)),
            ],
        ),
    ]
